// <auto-generated />
using EfCore.Shaman.Tests.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EfCore.Shaman.Tests.Migrations
{
    [DbContext(typeof(UnicodeTestDbContext))]
    [Migration("20171102152449_InitialUnicodeTestDbContext")]
    partial class InitialUnicodeTestDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCore.Shaman.Tests.Model.MySettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("MySettingsEntity");
                });

            modelBuilder.Entity("EfCore.Shaman.Tests.Model.UnicodeTestDbContext+SomeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Default")
                        .HasMaxLength(128);

                    b.Property<string>("DefaultNoLength");

                    b.Property<string>("NoUnicode")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.Property<string>("NoUnicodeNoLength")
                        .IsUnicode(false);

                    b.Property<string>("Unicode")
                        .HasMaxLength(128)
                        .IsUnicode(true);

                    b.Property<string>("UnicodeNoLength")
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.ToTable("SomeEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
